### ISSUE TITLE
Google Nest Mini/Audio volume doesn't return to previous level

### ISSUE THREAD

**Issue by mbuurman78** [TheFes/HA-configuration#106]
**Situation:**
Depending of the state (available or not) of a Google Nest device I'll send a TTS-message via your Google Home Resume script.
Most of the time this works flawless, but sometimes the volume doesn't return to the previous level. Not a big issue, but while having a phonecall with a customer it can be annoying. When multiple (usually 2) Google homes are playing music one of them returns to the previous volume but the other one creates a disco :-)
 
**HA Setup:**
Since not all Nest devices are turned on all day (entire desk is switched off including the Nest) or need to send out the specific message I first check the state in my Automation and use the 'Run in parallel' option to trigger the GH Resume script per GH Nest device. 
```
parallel:
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_boolean.iemand_op_de_bgg
            state: "off"
    then:
      - service: script.google_home_resume
        data:
          action:
            - service: tts.google_translate_say
              data:
                cache: false
                entity_id: media_player.woonkamer
                message: De wasmachine is klaar
                language: nl
              extra:
                volume: 0.5
          target:
            entity_id: media_player.woonkamer
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.zolder
            state: unavailable
    then:
      - service: script.google_home_resume
        data:
          action:
            - service: tts.google_translate_say
              data:
                cache: false
                entity_id: media_player.zolder
                message: De wasmachine is klaar
                language: nl
              extra:
                volume: 0.5
          target:
            entity_id: media_player.zolder
```

Could it be the case that the 'parallel' action is messing things up for the script?
The errors in the log give me the feeling that the first service-call removes the saved settings of the seconde service-call:

**Errors in log:**

```
 Logger: homeassistant.components.group

Source: components/group/__init__.py:350
Integration: Group (documentation, issues)
First occurred: November 10, 2023 at 19:59:53 (25 occurrences)
Last logged: 18:00:08

remove:Group 'resume_script_active_ghresume_01hfc76qwj21a43bddsq58m9b8' doesn't exist!
remove:Group 'resume_action_false_ghresume_01hfc76qwj21a43bddsq58m9b8' doesn't exist!
remove:Group 'resume_active_ghresume_01hfc76qwj21a43bddsq58m9b8' doesn't exist!
remove:Group 'resume_script_active_ghresume_01hfch6gnt715x6gpmcnrmyph4' doesn't exist!
remove:Group 'resume_action_false_ghresume_01hfch6gnt715x6gpmcnrmyph4' doesn't exist!`
```

**Traces:**
[trace script.google_home_resume_helper 2023-11-16T17_00_04.411251+00_00.json](https://github.com/TheFes/HA-configuration/files/13381316/trace.script.google_home_resume_helper.2023-11-16T17_00_04.411251%2B00_00.json)
[trace script.google_home_resume_helper 2023-11-16T17_00_00.786917+00_00.json](https://github.com/TheFes/HA-configuration/files/13381317/trace.script.google_home_resume_helper.2023-11-16T17_00_00.786917%2B00_00.json)
[trace script.google_home_resume_helper 2023-11-16T17_00_00.504021+00_00.json](https://github.com/TheFes/HA-configuration/files/13381318/trace.script.google_home_resume_helper.2023-11-16T17_00_00.504021%2B00_00.json)
[trace script.google_home_resume 2023-11-16T17_00_00.727097+00_00.json](https://github.com/TheFes/HA-configuration/files/13381319/trace.script.google_home_resume.2023-11-16T17_00_00.727097%2B00_00.json)
[trace script.google_home_resume 2023-11-16T17_00_00.063572+00_00.json](https://github.com/TheFes/HA-configuration/files/13381320/trace.script.google_home_resume.2023-11-16T17_00_00.063572%2B00_00.json)
[trace script.google_home_resume 2023-11-16T17_00_00.063244+00_00.json](https://github.com/TheFes/HA-configuration/files/13381321/trace.script.google_home_resume.2023-11-16T17_00_00.063244%2B00_00.json)

**Comment by TheFes** [comment]
I would do this differently:
```yaml
- variables:
    tts_target: >
      {% set woonkamer = [ 'media_player.woonkamer' ] if not is_state('input_boolean.iemand_op_de_bgg', 'off') else [] %}
      {% set zolder = [ 'media_player.zolder' ] if not is_state('media_player.zolder', 'unavailable') else [] %}
      {{ woonkamer + zolder }}
- if: "{{ tts_targets | count > 0 }}"
  then:
    - service: script.google_home_resume
      data:
        action:
          - service: tts.google_translate_say
            data:
              cache: false
              entity_id: "{{ tts_targets }}"
              message: De wasmachine is klaar
              language: nl
            extra:
              volume: 0.5
 ```
 That removes the need to run them in parallel, and you can do it in one script call.
BTW, it's not needed to define the `target` for the resume script, as that is the same target as in the service call

**Comment by mbuurman78** [comment]
I use the 'Visual Editor' and 'YAML' mixed and this is what HA creates.
This condition does not pass in the Visual Editor and Developer Tools:
```
- condition: template
   value_template: "{{ tts_targets | count > 0 }}"
```
This Jinja-template-magic is quite new to me, so maybe I'm missing something simple.

**Automation:**
```
alias: "Alerting: Melding bij wasmachine klaar"
description: Stuur een bericht als de wasmachine klaar is
trigger:
  - platform: numeric_state
    entity_id: sensor.2_zolder_wasmachine_power
    above: "40"
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.wasmachine_status
    data: {}
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: sensor.2_zolder_wasmachine_power
        for:
          hours: 0
          minutes: 1
          seconds: 0
        below: "2"
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.wasmachine_status
    data: {}
  - variables:
      tts_targets: >
        {% set woonkamer = [ 'media_player.woonkamer' ] if not is_state('input_boolean.iemand_op_de_bgg', 'off') else [] %}
        {% set zolder = [ 'media_player.zolder' ] if not is_state('media_player.zolder', 'unavailable') else [] %} 
        {{ woonkamer + zolder }}
  - parallel:
      - service: notify.telegram_group
        data:
          message: De wasmachine is klaar!
      - alias: Melding op Google Homes
        if:
          - condition: template
            value_template: "{{ tts_targets | count > 0 }}"
        then:
          - service: script.google_home_resume
            data:
              action:
                - service: tts.google_translate_say
                  data:
                    cache: false
                    entity_id: "{{ tts_targets }}"
                    message: De wasmachine is klaar
                    language: nl
                  extra:
                    volume: 0.5
```
