### ISSUE TITLE
Resume after image is sent to displays

### ISSUE THREAD

**Issue by joekaiser** [TheFes/HA-configuration#54]
Hey! I was able to get this working after just a few minutes of setup. Its great! Is there a way to have Resume work when I send an image to my google displays though?  

I have a script that, when the doorbell is pressed, a picture of the visitor is taken and cast to the google displays throughout the house. After 30s the image is removed. What would be the proper way to configure this so your resume script works? I have tried a few different ways, but my guess is that I need to update something in the automation you provide. Can you point me in the right direction? If it helps, here is my doorbell script.

Thanks so much! 💚 

```
doorbell_send_snapshot_to_displays:
  alias: Doorbell send snapshot to displays
  sequence:
  - service: camera.snapshot
    data:
      filename: /config/www/images/doorbellsnap.jpeg
    target:
      device_id: 4f727cb6d16f05386b5ab17047d76a08
  - service: media_player.play_media
    data:
      media_content_id: /local/images/doorbellsnap.jpeg
      media_content_type: image/jpeg
      announce: true
    target:
      entity_id:
      - media_player.office_display
      - media_player.kitchen_display
      - media_player.bedroom
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
      - media_player.kitchen_display
      - media_player.office_display
      - media_player.bedroom
  mode: single
```
