### ISSUE TITLE
Google Home Scripts resume issue

### ISSUE THREAD

**Issue by chicknlil** [TheFes/HA-configuration#61]
Was not able to upload the .JSON file.  It is available [here](https://www.dpaste.org/LfQJA).

Please advise if I can provide you with anything further.

**Comment by TheFes** [comment]
As I also replied on the forums:

Ah, I see it, that's an easy one to fix. Just add `group:` to your configuration.yaml (as also stated in the [General requirements](https://community.home-assistant.io/t/script-to-resume-google-cast-devices-after-they-have-been-interrupted-by-any-action/383896#general-4).

**Comment by chicknlil** [comment]
Do I just add group?  or do I have to list the devices in the group?

**Comment by TheFes** [comment]
Just add `group:`
Nothing else is needed. But without it you are not using the group integration, and therefore the `group.set` service I use in my script can not be found.

**Comment by chicknlil** [comment]
Okay. Did that, and had one of the speakers running spotify (and unrelated, my bedroom TV running Hulu). Another automation announced an event, and based on what I can tell, yours only tried to resume my TV, not the speaker.  So I'm still doing something wrong somewhere...

[Here's the file](https://www.dpaste.org/A66G0), from the helper script. There was no trace from the other one.

**Comment by TheFes** [comment]
It can not be the case that there is only a trace of the helper script, as the helper script is only started by the main script.

I do see that I need to build in some failsafe here, as it was not possible to resume the Hulu stream by the script.
The helper script is started separately per device, so for the other speaker it should have been another trace (you can navigate using the arrows)

**Comment by chicknlil** [comment]
So I found the only remaining instance of the script running yesterday, when I had Spotify running. I may be an idiot (I wouldn't doubt it) but I could not see any trace in that main script, and I checked all the arrows. I'll no doubt be listening to music later today though, and my event announcement automations will run to interrupt it. So I'll try to catch a trace at that point.

Thing of it is, my automations don't go to the TVs, just the speakers. So it was a bit weird that it wanted to turn that one on out of all of them. Though I've tweaked the script to reflect that the screened devices aren't part of my automations, so hopefully that'll resolve that (because it had a weird behavior this morning - it was turning my TV on from an off state).

**Comment by chicknlil** [comment]
Okay, it just interrupted Spotify, and Spotify didn't resume. And I've looked at every single Trace Timeline from that event, and they're all empty (from the main script) so I'm not sure what I'm missing here.

[Here's the main script](https://www.dpaste.org/bim1m) ...[Here's the helper script](https://www.dpaste.org/uRicF).

Getting frustrated by this.

**Comment by TheFes** [comment]
I can see that there are some things not right here. It seems the data from the automation is not used correctly. The automation only mentioned `media_player.speakers` as target, but the script performed actions on other players as well.

I'll have to look into this, but that will probably not be before Saturday, as I don't have access to a computer before then.

**Comment by chicknlil** [comment]
Okay. So it's not just me being an idiot? That's some relief.

That time I only had one device - my bedroom speaker - playing.

**Comment by TheFes** [comment]
What is the service call for the announcement you are using, to which speakers is it targeted?

**Comment by chicknlil** [comment]
`tts.cloud_say` is the service I use on all my automations that have an audio component, and the typical speaker target is `media_player.speakers`.

**Comment by TheFes** [comment]
I meant the full service call code including the target receiving the tts

**Comment by chicknlil** [comment]
Okay, I'm not sure I understand what you're looking for then. Where can I find this?

**Comment by TheFes** [comment]
I meant something like:
```yaml
service: tts.cloud_say
target: 
  entity_id: media_player.speakers
data:
  message: "Hello, I'm interrupting the speaker"
```

So, while on my mobile, I had a look at the traces you sent.

It looks like you are sending a TTS to the `media_player.speakers`

In the script you defined that as a speaker group, with the following members:
- media_player.ben_s_bedroom_speaker
- media_player.kitchen_display
- media_player.mom_s_bedroom_clock
 - media_player.living_room_speaker

There are two other cast entities which apparently are not belonging to this group:
 - media_player.ben_s_bedroom_tv
 - media_player.mom_s_bedroom_tv

Using that information, the script will try to resume anything playing on those 4 media players belonging to the group. If the group `media_player.speakers` was playing, it will resume the group itself.

In the trace I see actually none of the 4 group members was playing, one of them had Spotify active, but the state was `idle`, not playing.

That one was the only one sent to the helper script though, I'm not sure why the others were not. However as the player was `idle` and the volume was not changed, so no action was taken.

I'm not sure why this was not done for the other 3, but I'm not able to check that on mobile. 

If the speaker was actually playing, and not idle, it could be the automation is a bit too slow, and the player was already stopped before the data could be stored.

You could try if it works if you don't rely on the automation, but use the script directly, and add the TTS service call as the action in the script data.

If you have other traces, you can send them to see if it gives some more information.

**Comment by chicknlil** [comment]
Ah, got it now.  Here's one:

```
service: tts.cloud_say
    data:
      entity_id: media_player.speakers
      message: A Bruins event is upcoming!  Turn on your TV.
      cache: true
```

In that particular instance, I had spotify playing on `media_player.ben_s_bedroom_speaker` ... so it definitely wasn't idle.  So perhaps that's the issue - it's correctly detecting that Spotify is playing, but not the state?  Is that something I did wrong?

**Comment by TheFes** [comment]
No, I don't think you are doing something wrong.

The thing is that the automation is triggered when the TTS is already being sent to the device. So I suspect there is a timing issue here. Spotify is already being interrupted by the TTS message before the state can be stored by the automation.

The most reliable way to use the script is to call it directly instead of through the automation. In that way the data will be stored first, and then the service call will be started.

You can do that like this:
```yaml
service: script.turn_on
target: 
  entity_id: script.google_home_resume
data:
  variables:
    action:
      - service: tts.cloud_say
        data:
          entity_id: media_player.speakers
          message: A Bruins event is upcoming!  Turn on your TV.
          cache: true
```

**Comment by chicknlil** [comment]
Got it.  Updated all the automations that have a TTS element.  I'm starting Spotify on the speaker group as soon as it loads, and I've got an event announcement coming in about 20 minutes.  I'll report back on how it goes!

**Comment by chicknlil** [comment]
Nope,  Perhaps I set it up wrong.  This is the automation that just did the interrupting.  Should I perhaps add like a 1 second delay in there?

```
alias: Todoist
description: An automation to announce a task is due in Todoist.
trigger:
  - platform: calendar
    event: start
    offset: "-0:5:0"
    entity_id: calendar.todoist
condition:
  - condition: time
    before: "22:00:00"
    after: "06:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.google_home_resume
  - service: tts.cloud_say
    data:
      entity_id: media_player.speakers
      message: You have a task due.  Check Todo-ist for more information.
      cache: true
mode: single
```

**Comment by TheFes** [comment]
That's not what I proposed, the TTS action should be part of the script service call 

```yaml
alias: Todoist
description: An automation to announce a task is due in Todoist.
trigger:
  - platform: calendar
    event: start
    offset: "-0:5:0"
    entity_id: calendar.todoist
condition:
  - condition: time
    before: "22:00:00"
    after: "06:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
action:
  - service: script.turn_on
    target:
      entity_id: script.google_home_resume
    data:
      variables:
        action:
          - service: tts.cloud_say
            data:
              entity_id: media_player.speakers
              message: You have a task due.  Check Todo-ist for more information.
              cache: true
mode: single
```
