### ISSUE TITLE
Can't get groups to work

### ISSUE THREAD

**Issue by mellowism** [TheFes/HA-configuration#72]
Hi, 

This works fine when calling TTS with only the speaker playing music. But as soon as I call TTS on a group (e.g all google speakers) it doesn't resume playing.

I have a group with 3 speakers defined in the script.

It didn't support json files here so dpaste it is:
https://www.dpaste.org/t86mr
https://www.dpaste.org/osJc0

**Comment by TheFes** [comment]
What kind of groups are those? 
```json
"cast_entities": [
              "media_player.google_home_speaker",
              "media_player.google_smart_klokke",
              "media_player.gym_tv",
              "media_player.kitchen_display",
              "media_player.hovedsoverom_tv"
            ]
```
These entities are provided by the cast integration. I would expect your groups to be listed there as well..
Did you create the groups in Home Assistant, they should be created in the Google Home app

**Comment by mellowism** [comment]
Thanks, that did it for me. I don't create groups in the Google Home app, only in Home assistant. After testing with a group from the Google home app, it works as intended. 

FR: Could you add, so it works with groups created in HA? ;) I try to use HA for all functionality, and the manufactures apps as little as possible.

**Comment by TheFes** [comment]
THe Google Home groups have some advantages. They automatically sync the audio for example, so it's the same on all speakers.
But I will look into it.

**Comment by TheFes** [comment]
I can't use the groups to resume Spotify, but I wonder if you can actually use them to start Spotify on, because I think it will be seen as multiple targets (another advantage of Google Home groups, they are seen as a single target of Spotify, so they can be used to simultaneously cast Spotify to multiple devices)

Do you use these groups only as target for your announcements, or do you also use them as target for music/radio whatever?

**Comment by mellowism** [comment]
I haven't had any need for playing music simultaneously on multiple speakers yet. I only have 3, and they are on different floors. This isn't an issue when thinking of the speakers as TTS devices. 

Thanks for explaining how the groups work differently. It makes more sense then for music, creating the speaker groups in Google Home.

**Comment by TheFes** [comment]
So, you when do you use them? You are sending a TTS with the group as it's target?

**Comment by mellowism** [comment]
Yes

**Comment by mellowism** [comment]
Or, I did, after you said it only works with Google Groups, I have changed my automations and dashboards to use the Google group. :)

**Comment by TheFes** [comment]
It's not too difficult to let the automation work on HA groups as well, the problem is that it isn't triggered on the service call to the group, as the group is not a entity of the cast integration (and I check on that).

**Comment by TheFes** [comment]
Aaah, I see what the actual issue is now.
This event is sent first (to the group)
```yaml
event_type: call_service
data:
  domain: media_player
  service: play_media
  service_data:
    entity_id:
      - media_player.groep_zolder
    media_content_id: media-source://tts/google_cloud?message=Dit+is+een+test
    media_content_type: music
    announce: true
origin: LOCAL
time_fired: "2022-12-16T14:58:00.323316+00:00"
context:
  id: 01GMDQ2BFX00SXTKEZP0GGWTNH
  parent_id: null
  user_id: 24c8260fb51f4fb995e5aeaaaa3edd1b
```
as you can see, `announce: true` is set, as it should be for a TTS.

However, after that the message is actually sent to the group members:
```yaml
event_type: call_service
data:
  domain: media_player
  service: play_media
  service_data:
    entity_id:
      - media_player.zolder_mini_marleen
      - media_player.zolder_mini_martijn
    media_content_id: media-source://tts/google_cloud?message=Dit+is+een+test
    media_content_type: music
origin: LOCAL
time_fired: "2022-12-16T14:58:00.344042+00:00"
context:
  id: 01GMDQ2BFX00SXTKEZP0GGWTNH
  parent_id: null
  user_id: 24c8260fb51f4fb995e5aeaaaa3edd1b
```
Here `announce: true` is not set. 

Both events will trigger the automation, but the first will fail on the condition that the target should be a cast entity, the second fails because `announce: true` is not set.

I will create an issue for this. I will also build a fix into the automation so it will also check on the group members.
