### ISSUE TITLE
Google resume automation

### ISSUE THREAD

**Issue by jckickflip** [TheFes/HA-configuration#83]
I’m trying to use your resume automation and have it all installed. It triggers when a tts message comes across but it never resumed. Using a google home hub to test and Spotify is what im trying to resume. After the announcement it does bring up a music symbol for a second which is new but then just goes back to the clock with no music. I have checked the traces on the automation and the script and it shows it completed with no errors.

**Comment by TheFes** [comment]
Please send me the json files with the traces. I need them to determine what's going wrong

**Comment by jckickflip** [comment]
not sure what one you need.
automation - https://www.dpaste.org/QFPnz 
google home resume script - https://www.dpaste.org/hMPGB
google home resume helper script - https://www.dpaste.org/awHC9

**Comment by TheFes** [comment]
You didn't setup the speaker groups in the settings, so the script doesn't know that `media_player.whole_house` had `media_player.den_display` as it's member.
Therefor it doesn't know that it should be resumed.

**Comment by jckickflip** [comment]
So I added the groups and now it does not make the announcement it just goes back to the home screen on the google display or back to doing nothing on a regular google. It does not even make the announcement on googles that were not playing anything

https://www.dpaste.org/GsOtT
https://www.dpaste.org/k6mvw
https://www.dpaste.org/sCfnb

**Comment by TheFes** [comment]
Sorry for my lack in response since your last reply. I've been really busy.
I will look into it as soon as possible

**Comment by jckickflip** [comment]
Ok no problem

**Comment by TheFes** [comment]
Could you try calling the script directly, and not using the automation anymore?

```yaml
service: script.google_home_resume
data:
  target:
    entity_id: media_player.kitchen_display
  action:
    - service: tts.google_translate
      target:
        entity_id: media_player.whole_house
      data:
        message: "Richie is here, Hide!"
```
