### ISSUE TITLE
Slug problem in Goolge_home_resume script?

### ISSUE THREAD

**Issue by Rikkie80** [TheFes/HA-configuration#84]
Not sure what is wrong...

In log:
00 🔊 Google Home Resume: Error executing script. Invalid data for call_service at pos 10: invalid slug resume_script_active_ghresume_01GXZT6QX7S12VH5VTKFWDVEN2 (try resume_script_active_ghresume_01gxzt6qx7s12vh5vtkfwdven2) for dictionary value @ data['object_id']

```
alias: "Remove entity + members from group"
                    service: group.set
                    data:
                      object_id: resume_script_active_ghresume_{{ context.id | lower }}
                      name: "Entities currently active with Google Home Resume script"
                      icon: mdi:play-box
                      entities: >
                        {%- set g = 'group.resume_script_active_ghresume_' ~ context.id | lower %}
                        {%- set current = state_attr(g, 'entity_id') %}
                        {{ iif(current == none, [], current) | reject('in', [player.entity_id] + player.members) | list }}
                  - alias: "Send event that script is finished"
                    event: script_finished_{{ context.id | lower }}
```
Don't understand why capitals are used while the script has {{content.id | lower }}?
Can you help?
