### ISSUE TITLE
Odd error where TTS only works on every 'even' numbered service call

### ISSUE THREAD

**Issue by rahulpdev** [TheFes/HA-configuration#85]
I just discovered the Google Home Resume Package and after installing the files I started to use it for the first time and have immediately experienced this issue.

I have a script that actions a TTS to my Google Nest Hub with a template message. When I call the script service I pass in the actual message under a data header. Before installing the Google Home Resume Package this script worked just fine:
```
alias: TEST say TTS message
sequence:
  - service: tts.cloud_say
    data:
      cache: true
      entity_id: media_player.kitchen_display
      message: "{{ sentence }}"
mode: single
```
This is an example of a call to the script service providing the actual message: 
```
service: script.test_say_tts_message
data:
  sentence: This is a test
```
Now, when I call the script the message does not play as expected. I can visually see on the Next Hub that a TTS message is initiating but it does not actually execute. (I can see the device volume change to my `default_volume_level` and I briefly see the blue Google Cast icon on the screen but then the screen goes back to its previous state.)

Interestingly, if I call the service **repeatedly and in rapid succession**, the TTS DOES work but only on every nth attempt where n is an **even** number. For example, if I call the script repeatedly (in Developer Tools) it will work and play the message on the 2nd/4th/6th/8th, etc call only.

I've attached the traces for the automation and both scripts. I'm not sure how the package is supposed to work but the even numbered call does not generate a trace in the scripts, only in the automation, so I've only attached the automation trace for the successful TTS call.

Unsuccessful TTS call:
[trace automation.00_google_home_automatic_resume 2023-04-16T15_00_19.124390+00_00](https://www.dpaste.org/x0EXK)
[trace script.google_home_resume 2023-04-16T15_00_20.990841+00_00](https://www.dpaste.org/ryVR6)
[trace script.google_home_resume_helper 2023-04-16T15_00_34.206156+00_00](https://www.dpaste.org/TTHu0)

Successfull TTS call:
[trace automation.00_google_home_automatic_resume 2023-04-16T15_02_52.067968+00_00](https://www.dpaste.org/oAwQk)

**Comment by TheFes** [comment]
I would advice not to rely on the automation, and call the script yourself
```yaml
service: script.google_home_resume
data:
  target:
    entity_id: media_player.kitchen_display
  action:
    - service: script.test_say_tts_message
      data:
        sentence: This is a test
```
